version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-docker
    restart: always
    ports: 
      - 27018:27017
    volumes:
      - db-data:/data/db
  url-shortener:
    image: url-shortener
    container_name: url-shortener
    restart: always
    depends_on: 
      - mongodb
    ports:
      - 3000:3000
volumes:
  db-data:
    driver: local